/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.8
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *mem_usage;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_4;
    QLabel *label_43;
    QPushButton *pushButton_41;
    QPushButton *pushButton_42;
    QPushButton *pushButton_43;
    QPushButton *pushButton_44;
    QPushButton *pushButton_45;
    QPushButton *pushButton_46;
    QPushButton *pushButton_47;
    QPushButton *pushButton_48;
    QPushButton *pushButton_49;
    QPushButton *pushButton_50;
    QPushButton *pushButton_51;
    QPushButton *pushButton_52;
    QPushButton *pushButton_53;
    QPushButton *pushButton_54;
    QPushButton *pushButton_55;
    QPushButton *pushButton_56;
    QPushButton *pushButton_57;
    QPushButton *pushButton_58;
    QPushButton *pushButton_59;
    QPushButton *pushButton_60;
    QPushButton *pushButton_61;
    QPushButton *pushButton_62;
    QPushButton *pushButton_63;
    QPushButton *pushButton_64;
    QPushButton *pushButton_65;
    QPushButton *pushButton_66;
    QPushButton *pushButton_67;
    QPushButton *pushButton_68;
    QPushButton *pushButton_69;
    QPushButton *pushButton_70;
    QPushButton *pushButton_71;
    QPushButton *pushButton_72;
    QPushButton *pushButton_73;
    QPushButton *pushButton_74;
    QPushButton *pushButton_75;
    QPushButton *pushButton_76;
    QPushButton *pushButton_77;
    QPushButton *pushButton_78;
    QPushButton *pushButton_79;
    QPushButton *pushButton_80;
    QPushButton *pushButton_81;
    QPushButton *pushButton_82;
    QPushButton *pushButton_83;
    QPushButton *pushButton_84;
    QPushButton *pushButton_85;
    QPushButton *pushButton_86;
    QPushButton *pushButton_87;
    QPushButton *pushButton_88;
    QPushButton *pushButton_89;
    QPushButton *pushButton_90;
    QPushButton *btn_start;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1075, 820);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        label = new QLabel(centralwidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(430, 30, 131, 17));
        label_2 = new QLabel(centralwidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(20, 720, 131, 17));
        label_3 = new QLabel(centralwidget);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(180, 720, 131, 17));
        mem_usage = new QLabel(centralwidget);
        mem_usage->setObjectName(QString::fromUtf8("mem_usage"));
        mem_usage->setGeometry(QRect(40, 740, 111, 20));
        label_5 = new QLabel(centralwidget);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(230, 750, 41, 17));
        label_6 = new QLabel(centralwidget);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(750, 710, 81, 17));
        label_4 = new QLabel(centralwidget);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(340, 720, 131, 17));
        label_43 = new QLabel(centralwidget);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(350, 750, 41, 17));
        pushButton_41 = new QPushButton(centralwidget);
        pushButton_41->setObjectName(QString::fromUtf8("pushButton_41"));
        pushButton_41->setGeometry(QRect(610, 90, 71, 111));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/imagenes/SW_back.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_41->setIcon(icon);
        pushButton_41->setIconSize(QSize(150, 115));
        pushButton_42 = new QPushButton(centralwidget);
        pushButton_42->setObjectName(QString::fromUtf8("pushButton_42"));
        pushButton_42->setGeometry(QRect(430, 90, 71, 111));
        pushButton_42->setIcon(icon);
        pushButton_42->setIconSize(QSize(150, 115));
        pushButton_43 = new QPushButton(centralwidget);
        pushButton_43->setObjectName(QString::fromUtf8("pushButton_43"));
        pushButton_43->setGeometry(QRect(520, 90, 71, 111));
        pushButton_43->setIcon(icon);
        pushButton_43->setIconSize(QSize(150, 115));
        pushButton_44 = new QPushButton(centralwidget);
        pushButton_44->setObjectName(QString::fromUtf8("pushButton_44"));
        pushButton_44->setGeometry(QRect(70, 90, 71, 111));
        pushButton_44->setIcon(icon);
        pushButton_44->setIconSize(QSize(150, 115));
        pushButton_45 = new QPushButton(centralwidget);
        pushButton_45->setObjectName(QString::fromUtf8("pushButton_45"));
        pushButton_45->setGeometry(QRect(250, 90, 71, 111));
        pushButton_45->setIcon(icon);
        pushButton_45->setIconSize(QSize(150, 115));
        pushButton_46 = new QPushButton(centralwidget);
        pushButton_46->setObjectName(QString::fromUtf8("pushButton_46"));
        pushButton_46->setGeometry(QRect(790, 90, 71, 111));
        pushButton_46->setIcon(icon);
        pushButton_46->setIconSize(QSize(150, 115));
        pushButton_47 = new QPushButton(centralwidget);
        pushButton_47->setObjectName(QString::fromUtf8("pushButton_47"));
        pushButton_47->setGeometry(QRect(880, 90, 71, 111));
        pushButton_47->setIcon(icon);
        pushButton_47->setIconSize(QSize(150, 115));
        pushButton_48 = new QPushButton(centralwidget);
        pushButton_48->setObjectName(QString::fromUtf8("pushButton_48"));
        pushButton_48->setGeometry(QRect(160, 90, 71, 111));
        pushButton_48->setIcon(icon);
        pushButton_48->setIconSize(QSize(150, 115));
        pushButton_49 = new QPushButton(centralwidget);
        pushButton_49->setObjectName(QString::fromUtf8("pushButton_49"));
        pushButton_49->setGeometry(QRect(340, 90, 71, 111));
        pushButton_49->setIcon(icon);
        pushButton_49->setIconSize(QSize(150, 115));
        pushButton_50 = new QPushButton(centralwidget);
        pushButton_50->setObjectName(QString::fromUtf8("pushButton_50"));
        pushButton_50->setGeometry(QRect(700, 90, 71, 111));
        pushButton_50->setIcon(icon);
        pushButton_50->setIconSize(QSize(150, 115));
        pushButton_51 = new QPushButton(centralwidget);
        pushButton_51->setObjectName(QString::fromUtf8("pushButton_51"));
        pushButton_51->setGeometry(QRect(520, 210, 71, 111));
        pushButton_51->setIcon(icon);
        pushButton_51->setIconSize(QSize(150, 115));
        pushButton_52 = new QPushButton(centralwidget);
        pushButton_52->setObjectName(QString::fromUtf8("pushButton_52"));
        pushButton_52->setGeometry(QRect(70, 210, 71, 111));
        pushButton_52->setIcon(icon);
        pushButton_52->setIconSize(QSize(150, 115));
        pushButton_53 = new QPushButton(centralwidget);
        pushButton_53->setObjectName(QString::fromUtf8("pushButton_53"));
        pushButton_53->setGeometry(QRect(340, 210, 71, 111));
        pushButton_53->setIcon(icon);
        pushButton_53->setIconSize(QSize(150, 115));
        pushButton_54 = new QPushButton(centralwidget);
        pushButton_54->setObjectName(QString::fromUtf8("pushButton_54"));
        pushButton_54->setGeometry(QRect(700, 210, 71, 111));
        pushButton_54->setIcon(icon);
        pushButton_54->setIconSize(QSize(150, 115));
        pushButton_55 = new QPushButton(centralwidget);
        pushButton_55->setObjectName(QString::fromUtf8("pushButton_55"));
        pushButton_55->setGeometry(QRect(790, 210, 71, 111));
        pushButton_55->setIcon(icon);
        pushButton_55->setIconSize(QSize(150, 115));
        pushButton_56 = new QPushButton(centralwidget);
        pushButton_56->setObjectName(QString::fromUtf8("pushButton_56"));
        pushButton_56->setGeometry(QRect(430, 210, 71, 111));
        pushButton_56->setIcon(icon);
        pushButton_56->setIconSize(QSize(150, 115));
        pushButton_57 = new QPushButton(centralwidget);
        pushButton_57->setObjectName(QString::fromUtf8("pushButton_57"));
        pushButton_57->setGeometry(QRect(610, 210, 71, 111));
        pushButton_57->setIcon(icon);
        pushButton_57->setIconSize(QSize(150, 115));
        pushButton_58 = new QPushButton(centralwidget);
        pushButton_58->setObjectName(QString::fromUtf8("pushButton_58"));
        pushButton_58->setGeometry(QRect(160, 210, 71, 111));
        pushButton_58->setIcon(icon);
        pushButton_58->setIconSize(QSize(150, 115));
        pushButton_59 = new QPushButton(centralwidget);
        pushButton_59->setObjectName(QString::fromUtf8("pushButton_59"));
        pushButton_59->setGeometry(QRect(250, 210, 71, 111));
        pushButton_59->setIcon(icon);
        pushButton_59->setIconSize(QSize(150, 115));
        pushButton_60 = new QPushButton(centralwidget);
        pushButton_60->setObjectName(QString::fromUtf8("pushButton_60"));
        pushButton_60->setGeometry(QRect(880, 210, 71, 111));
        pushButton_60->setIcon(icon);
        pushButton_60->setIconSize(QSize(150, 115));
        pushButton_61 = new QPushButton(centralwidget);
        pushButton_61->setObjectName(QString::fromUtf8("pushButton_61"));
        pushButton_61->setGeometry(QRect(880, 330, 71, 111));
        pushButton_61->setIcon(icon);
        pushButton_61->setIconSize(QSize(150, 115));
        pushButton_62 = new QPushButton(centralwidget);
        pushButton_62->setObjectName(QString::fromUtf8("pushButton_62"));
        pushButton_62->setGeometry(QRect(70, 330, 71, 111));
        pushButton_62->setIcon(icon);
        pushButton_62->setIconSize(QSize(150, 115));
        pushButton_63 = new QPushButton(centralwidget);
        pushButton_63->setObjectName(QString::fromUtf8("pushButton_63"));
        pushButton_63->setGeometry(QRect(700, 330, 71, 111));
        pushButton_63->setIcon(icon);
        pushButton_63->setIconSize(QSize(150, 115));
        pushButton_64 = new QPushButton(centralwidget);
        pushButton_64->setObjectName(QString::fromUtf8("pushButton_64"));
        pushButton_64->setGeometry(QRect(340, 330, 71, 111));
        pushButton_64->setIcon(icon);
        pushButton_64->setIconSize(QSize(150, 115));
        pushButton_65 = new QPushButton(centralwidget);
        pushButton_65->setObjectName(QString::fromUtf8("pushButton_65"));
        pushButton_65->setGeometry(QRect(610, 330, 71, 111));
        pushButton_65->setIcon(icon);
        pushButton_65->setIconSize(QSize(150, 115));
        pushButton_66 = new QPushButton(centralwidget);
        pushButton_66->setObjectName(QString::fromUtf8("pushButton_66"));
        pushButton_66->setGeometry(QRect(790, 330, 71, 111));
        pushButton_66->setIcon(icon);
        pushButton_66->setIconSize(QSize(150, 115));
        pushButton_67 = new QPushButton(centralwidget);
        pushButton_67->setObjectName(QString::fromUtf8("pushButton_67"));
        pushButton_67->setGeometry(QRect(430, 330, 71, 111));
        pushButton_67->setIcon(icon);
        pushButton_67->setIconSize(QSize(150, 115));
        pushButton_68 = new QPushButton(centralwidget);
        pushButton_68->setObjectName(QString::fromUtf8("pushButton_68"));
        pushButton_68->setGeometry(QRect(520, 330, 71, 111));
        pushButton_68->setIcon(icon);
        pushButton_68->setIconSize(QSize(150, 115));
        pushButton_69 = new QPushButton(centralwidget);
        pushButton_69->setObjectName(QString::fromUtf8("pushButton_69"));
        pushButton_69->setGeometry(QRect(160, 330, 71, 111));
        pushButton_69->setIcon(icon);
        pushButton_69->setIconSize(QSize(150, 115));
        pushButton_70 = new QPushButton(centralwidget);
        pushButton_70->setObjectName(QString::fromUtf8("pushButton_70"));
        pushButton_70->setGeometry(QRect(250, 330, 71, 111));
        pushButton_70->setIcon(icon);
        pushButton_70->setIconSize(QSize(150, 115));
        pushButton_71 = new QPushButton(centralwidget);
        pushButton_71->setObjectName(QString::fromUtf8("pushButton_71"));
        pushButton_71->setGeometry(QRect(250, 450, 71, 111));
        pushButton_71->setIcon(icon);
        pushButton_71->setIconSize(QSize(150, 115));
        pushButton_72 = new QPushButton(centralwidget);
        pushButton_72->setObjectName(QString::fromUtf8("pushButton_72"));
        pushButton_72->setGeometry(QRect(70, 450, 71, 111));
        pushButton_72->setIcon(icon);
        pushButton_72->setIconSize(QSize(150, 115));
        pushButton_73 = new QPushButton(centralwidget);
        pushButton_73->setObjectName(QString::fromUtf8("pushButton_73"));
        pushButton_73->setGeometry(QRect(880, 450, 71, 111));
        pushButton_73->setIcon(icon);
        pushButton_73->setIconSize(QSize(150, 115));
        pushButton_74 = new QPushButton(centralwidget);
        pushButton_74->setObjectName(QString::fromUtf8("pushButton_74"));
        pushButton_74->setGeometry(QRect(430, 450, 71, 111));
        pushButton_74->setIcon(icon);
        pushButton_74->setIconSize(QSize(150, 115));
        pushButton_75 = new QPushButton(centralwidget);
        pushButton_75->setObjectName(QString::fromUtf8("pushButton_75"));
        pushButton_75->setGeometry(QRect(160, 450, 71, 111));
        pushButton_75->setIcon(icon);
        pushButton_75->setIconSize(QSize(150, 115));
        pushButton_76 = new QPushButton(centralwidget);
        pushButton_76->setObjectName(QString::fromUtf8("pushButton_76"));
        pushButton_76->setGeometry(QRect(700, 450, 71, 111));
        pushButton_76->setIcon(icon);
        pushButton_76->setIconSize(QSize(150, 115));
        pushButton_77 = new QPushButton(centralwidget);
        pushButton_77->setObjectName(QString::fromUtf8("pushButton_77"));
        pushButton_77->setGeometry(QRect(610, 450, 71, 111));
        pushButton_77->setIcon(icon);
        pushButton_77->setIconSize(QSize(150, 115));
        pushButton_78 = new QPushButton(centralwidget);
        pushButton_78->setObjectName(QString::fromUtf8("pushButton_78"));
        pushButton_78->setGeometry(QRect(790, 450, 71, 111));
        pushButton_78->setIcon(icon);
        pushButton_78->setIconSize(QSize(150, 115));
        pushButton_79 = new QPushButton(centralwidget);
        pushButton_79->setObjectName(QString::fromUtf8("pushButton_79"));
        pushButton_79->setGeometry(QRect(520, 450, 71, 111));
        pushButton_79->setIcon(icon);
        pushButton_79->setIconSize(QSize(150, 115));
        pushButton_80 = new QPushButton(centralwidget);
        pushButton_80->setObjectName(QString::fromUtf8("pushButton_80"));
        pushButton_80->setGeometry(QRect(340, 450, 71, 111));
        pushButton_80->setIcon(icon);
        pushButton_80->setIconSize(QSize(150, 115));
        pushButton_81 = new QPushButton(centralwidget);
        pushButton_81->setObjectName(QString::fromUtf8("pushButton_81"));
        pushButton_81->setGeometry(QRect(430, 570, 71, 111));
        pushButton_81->setIcon(icon);
        pushButton_81->setIconSize(QSize(150, 115));
        pushButton_82 = new QPushButton(centralwidget);
        pushButton_82->setObjectName(QString::fromUtf8("pushButton_82"));
        pushButton_82->setGeometry(QRect(790, 570, 71, 111));
        pushButton_82->setIcon(icon);
        pushButton_82->setIconSize(QSize(150, 115));
        pushButton_83 = new QPushButton(centralwidget);
        pushButton_83->setObjectName(QString::fromUtf8("pushButton_83"));
        pushButton_83->setGeometry(QRect(880, 570, 71, 111));
        pushButton_83->setIcon(icon);
        pushButton_83->setIconSize(QSize(150, 115));
        pushButton_84 = new QPushButton(centralwidget);
        pushButton_84->setObjectName(QString::fromUtf8("pushButton_84"));
        pushButton_84->setGeometry(QRect(520, 570, 71, 111));
        pushButton_84->setIcon(icon);
        pushButton_84->setIconSize(QSize(150, 115));
        pushButton_85 = new QPushButton(centralwidget);
        pushButton_85->setObjectName(QString::fromUtf8("pushButton_85"));
        pushButton_85->setGeometry(QRect(700, 570, 71, 111));
        pushButton_85->setIcon(icon);
        pushButton_85->setIconSize(QSize(150, 115));
        pushButton_86 = new QPushButton(centralwidget);
        pushButton_86->setObjectName(QString::fromUtf8("pushButton_86"));
        pushButton_86->setGeometry(QRect(250, 570, 71, 111));
        pushButton_86->setIcon(icon);
        pushButton_86->setIconSize(QSize(150, 115));
        pushButton_87 = new QPushButton(centralwidget);
        pushButton_87->setObjectName(QString::fromUtf8("pushButton_87"));
        pushButton_87->setGeometry(QRect(610, 570, 71, 111));
        pushButton_87->setIcon(icon);
        pushButton_87->setIconSize(QSize(150, 115));
        pushButton_88 = new QPushButton(centralwidget);
        pushButton_88->setObjectName(QString::fromUtf8("pushButton_88"));
        pushButton_88->setGeometry(QRect(160, 570, 71, 111));
        pushButton_88->setIcon(icon);
        pushButton_88->setIconSize(QSize(150, 115));
        pushButton_89 = new QPushButton(centralwidget);
        pushButton_89->setObjectName(QString::fromUtf8("pushButton_89"));
        pushButton_89->setGeometry(QRect(340, 570, 71, 111));
        pushButton_89->setIcon(icon);
        pushButton_89->setIconSize(QSize(150, 115));
        pushButton_90 = new QPushButton(centralwidget);
        pushButton_90->setObjectName(QString::fromUtf8("pushButton_90"));
        pushButton_90->setGeometry(QRect(70, 570, 71, 111));
        pushButton_90->setIcon(icon);
        pushButton_90->setIconSize(QSize(150, 115));
        btn_start = new QPushButton(centralwidget);
        btn_start->setObjectName(QString::fromUtf8("btn_start"));
        btn_start->setGeometry(QRect(510, 730, 89, 25));
        MainWindow->setCentralWidget(centralwidget);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        label->setText(QApplication::translate("MainWindow", "Juego de memoria", nullptr));
        label_2->setText(QApplication::translate("MainWindow", "Uso de memoria:", nullptr));
        label_3->setText(QApplication::translate("MainWindow", "Tiempo restante:", nullptr));
        mem_usage->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_5->setText(QApplication::translate("MainWindow", "null", nullptr));
        label_6->setText(QApplication::translate("MainWindow", "Power Ups", nullptr));
        label_4->setText(QApplication::translate("MainWindow", "Turno de:", nullptr));
        label_43->setText(QApplication::translate("MainWindow", "null", nullptr));
        pushButton_41->setText(QString());
        pushButton_42->setText(QString());
        pushButton_43->setText(QString());
        pushButton_44->setText(QString());
        pushButton_45->setText(QString());
        pushButton_46->setText(QString());
        pushButton_47->setText(QString());
        pushButton_48->setText(QString());
        pushButton_49->setText(QString());
        pushButton_50->setText(QString());
        pushButton_51->setText(QString());
        pushButton_52->setText(QString());
        pushButton_53->setText(QString());
        pushButton_54->setText(QString());
        pushButton_55->setText(QString());
        pushButton_56->setText(QString());
        pushButton_57->setText(QString());
        pushButton_58->setText(QString());
        pushButton_59->setText(QString());
        pushButton_60->setText(QString());
        pushButton_61->setText(QString());
        pushButton_62->setText(QString());
        pushButton_63->setText(QString());
        pushButton_64->setText(QString());
        pushButton_65->setText(QString());
        pushButton_66->setText(QString());
        pushButton_67->setText(QString());
        pushButton_68->setText(QString());
        pushButton_69->setText(QString());
        pushButton_70->setText(QString());
        pushButton_71->setText(QString());
        pushButton_72->setText(QString());
        pushButton_73->setText(QString());
        pushButton_74->setText(QString());
        pushButton_75->setText(QString());
        pushButton_76->setText(QString());
        pushButton_77->setText(QString());
        pushButton_78->setText(QString());
        pushButton_79->setText(QString());
        pushButton_80->setText(QString());
        pushButton_81->setText(QString());
        pushButton_82->setText(QString());
        pushButton_83->setText(QString());
        pushButton_84->setText(QString());
        pushButton_85->setText(QString());
        pushButton_86->setText(QString());
        pushButton_87->setText(QString());
        pushButton_88->setText(QString());
        pushButton_89->setText(QString());
        pushButton_90->setText(QString());
        btn_start->setText(QApplication::translate("MainWindow", "Empezar", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
